# fly.toml app configuration file generated for swapper on 2023-06-27T13:52:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "swapper"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
